import { useEffect } from 'react';

export default function Sitemap() {
  useEffect(() => {
    // This page serves as a route that generates the sitemap
    // The actual sitemap is generated by the backend function
    window.location.href = '/api/generateSitemap';
  }, []);

  return null;
}